name: Build/release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: setup node env
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16

      - name: Install Modules and Publish build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn run release
